### ISSUE TITLE
Tooltips overlap Mine & Slash stat tooltips

### ISSUE THREAD

**Issue by WenXin20** [ercanserteli/xercamods#1]
`Minecraft v1.14.4`
`Forge v28.1.96`
[`Mine & Slash v2.9.3`](https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded) 
[`Mine & Slash Compat v1.4.0`](https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-auto-compatibility) 
`Xerca v1.2`

It would be great if this could be fixed to prevent overlaps, thanks!
![2019-11-29_22 01 43](https://user-images.githubusercontent.com/12000593/69895536-4447ce00-12f7-11ea-97d7-f210fd472c48.png)

**Comment by ercanserteli** [comment]
I hadn't heard about the Mine & Slash mod before, but it seems they added those tooltips in Mine & Slash Compat. Knife in XercaMod doesn't have anything special that affects the tooltip, so I do not have a way to fix this. I suggest you contact the author of the Mine & Slash Compat mod instead.

**Comment by WenXin20** [comment]
I already contacted Mine & Slash first at their [discord](https://discord.gg/4vEKxfK), but was recommended to contact you, he said it's because an override was being forced for the tooltip.

**Comment by ercanserteli** [comment]
I checked more thoroughly this time and I am sure that there is no special override or anything about the tooltip. The knife class simply returns attack damage bonuses from the getAttributeModifiers method in the same way as vanilla items and the only tooltip it (and other tools) has is generated by the game normally. Sorry but I cannot help with this issue.
