### ISSUE TITLE
[Suggestions] 1.15.2

### ISSUE THREAD

**Issue by D-Bigboy-302** [ercanserteli/xercamods#10]
Just a few suggestions/ideas. 

- Add material variants for the knife. I.e, Diamond, gold etc.
- Maybe an EnderFlask for Splash Potions, or a sling. (For holding more splash potions)
-More vanilla enchantments for Hammer and Knife. I.e, Smite for Hammer and Sharpness for knife.

Love your mod! Thank you for taking the time to make it!

**Comment by ercanserteli** [comment]
Thank you for the suggestions, I added potion launcher (ender flask for splash potions) and vanilla enchantments for hammer and knife in the newest update.
