### ISSUE TITLE
[1.20.1] Music Sheet is off by a half-step

### ISSUE THREAD

**Issue by FoxMcloud5655** [ercanserteli/xercamods#112]
When using the instruments and playing on them using a keyboard, the note starts at A when you press Q on the keyboard.  If you open up a Music Sheet and press Q on the keyboard, the note that plays is A#/Bb.

Xerca Music Maker version: 1.20.1-1.0.0

**Comment by ercanserteli** [comment]
Fixed (81cc005e48a15346355aeb66d7d547945b649d82) and updated in 1.20.1-1.0.1
