### ISSUE TITLE
Issue with the music box when attempting to break it!

### ISSUE THREAD

**Issue by BqqtBG** [ercanserteli/xercamods#113]
The issue is as follows: when placing the music box on the ground and attempting to break it, it disappears for 1 second and then reappears in the same place without dropping anything. Also, attempting to break it multiple times causes a server crash.
Xerca Music Maker version: 1.20.1-1.0.0

https://github.com/ercanserteli/xercamods/assets/25131118/ed7e9e84-1788-4189-a624-4eaa98631aa5

**Comment by ercanserteli** [comment]
Fixed (951d6cf) and updated in 1.20.1-1.0.1
