### ISSUE TITLE
[Joy of painting] Fabric 1.20.1 v1.0 No crafting recipes

### ISSUE THREAD

**Issue by Zouzs** [ercanserteli/xercamods#117]
The mod works fine but there is no crafting recipe in any item
![2024-04-02_20 05 14](https://github.com/ercanserteli/xercamods/assets/44651203/4ebddc13-c906-4c8b-8d1c-bcdc73ed51f8)
![2024-04-02_20 05 28](https://github.com/ercanserteli/xercamods/assets/44651203/4f902a3d-1df3-4518-ada6-975709f2a553)

**Comment by Zouzs** [comment]
My bad, dumb mistake, the mod wasn't uploaded in the server:P

**Comment by ercanserteli** [comment]
:)
