### ISSUE TITLE
xercapaint rendering crash with most likely shaders

### ISSUE THREAD

**Issue by loti1234** [ercanserteli/xercamods#121]
[crash-2024-06-07_20.47.32-client.txt](https://github.com/user-attachments/files/15743863/crash-2024-06-07_20.47.32-client.txt)

[latest.log](https://github.com/user-attachments/files/15743868/latest.log)

**Comment by loti1234** [comment]
btw this is in 1.19.2 forge

**Comment by loti1234** [comment]
noticed that this also happens even without enabling shaders

**Comment by ercanserteli** [comment]
This is fixed with 67c95e06d8c14e5772ace4472d8d31b269716f06
