### ISSUE TITLE
[Joy of Painting] Names on Jade appear blank

### ISSUE THREAD

**Issue by alboxer2000** [ercanserteli/xercamods#134]
![2024-10-06_09 55 09](https://github.com/user-attachments/assets/8709c04b-39db-4561-a448-2de3663a75a5)
When I look at a placed canvas, the name appears blank (with no name in the lang file)

**Comment by ercanserteli** [comment]
Fixed in [8415fe1](https://github.com/ercanserteli/xercamods/commit/8415fe15f8b0ab65621a71e55fb9109b01c16caa) (1.21.1-1.0.1)

**Comment by johndelker** [comment]
Can this change be pushed to 1.20.1 as well?
