### ISSUE TITLE
Paintings appear white after a while

### ISSUE THREAD

**Issue by farsenfsd** [ercanserteli/xercamods#135]
We upgraded our server from 1.20.1 to 1.21.1 and since then we have this problem, it happens with both old and new paintings we've been making. 

Taking the painting and placing it again loads it correctly, but after some time it happens again.

**Comment by JpbmOfficial** [comment]
The same happens to me, I don't really get what may be the reason.
If we take it from the wall and place it again, then it returns to normal but after a while turns white again...

**Comment by ercanserteli** [comment]
This should be fixed in [8415fe1](https://github.com/ercanserteli/xercamods/commit/8415fe15f8b0ab65621a71e55fb9109b01c16caa) (1.21.1-1.0.1)
