### ISSUE TITLE
Music Maker Mod 1.21.1-1.0.0 Incorrectly Listed as NeoForge

### ISSUE THREAD

**Issue by TheButterbrotMan** [ercanserteli/xercamods#136]
The "xerxcamusic-1.21.1-1.0.0.jar" file is labeled as compatible with NeoForge on CurseForge, but an error occurs at startup indicating it is a Fabric mod.

**Comment by ercanserteli** [comment]
It isn't incorrect, you need to install Sinytra Connector as mentioned in the mod page
