### ISSUE TITLE
Carved Acacia Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [ercanserteli/xercamods#21]
`Minecraft v1.15.2`
`Xerca v2.6`

Carved Acacia renders incorrectly when placed underwater. It looks like water is flowing down it's sides. Using the boolean `shouldDisplayFluidOverlay` should fix this.

It would also be nice to see waterloggable rope.

**Comment by ercanserteli** [comment]
Fixed f4039712 (no waterloggable rope yet). Thanks for reporting.

**Comment by WenXin20** [comment]
Alright, thanks!
