### ISSUE TITLE
[Suggestion] ingame info / tooltips

### ISSUE THREAD

**Issue by Zygus42** [ercanserteli/xercamods#23]
In a modpack on a server, people usually look at items and if they can't figure out what it does, they chuck it in a chest and forget about it rather than going and looking it up.  Would be great to have a little tooltip on each item - for example on a Scythe, could be: "won't harvest non-fully grown food plants".

**Comment by ercanserteli** [comment]
Added 5aff4a48. Thanks for the suggestion, it makes a lot of sense.
