### ISSUE TITLE
Suggestion: Placeable Teapot

### ISSUE THREAD

**Issue by IdrisQe** [ercanserteli/xercamods#3]
It'd be nice to be able to just pour yourself a cup of hot tea by going by a teapot and right clicking it with a cup in hand. I know some tea mods do this already, but many overcomplicate it.
Also adding milk to tea would be a great addition, perhaps making the tea give you a status that makes you temporarily immune to any statuses that milk can cure?

(Also perhaps being able to fill bottles with milk for on-the-go status healing. I know a seperate Bottled Milk mod exists, and that you can make Glasses of Milk with this mod, but given this mod is full of general improvements, I feel it'd be a great one to add, simple bottles of milk, perhaps stackable, so you don't need to carry around lidless glasses or huge buckets, which feels weird, even in Minecraft.)

**Comment by ercanserteli** [comment]
Thanks for the suggestion, I added placeable teapots in the new update.
