### ISSUE TITLE
Crash when using music note "Division by zero"

### ISSUE THREAD

**Issue by NikkeKatski** [ercanserteli/xercamods#33]
[crash-2021-03-02_09.13.51-client.txt](https://github.com/ercanserteli/xercamods/files/6069792/crash-2021-03-02_09.13.51-client.txt)

When opening an unedited (and even with one edited) music sheet my game crashes, telling me it was due to division by zero. This was on a Valhesia 3 server on the version 3.1.8a. The music sheet was renamed via anvil before the first time I opened up the sheet to edit it but I'm not sure if that is related. This crash causes consistently with the musicsheets that do crash my game but never happens with the few that dont?

**Comment by ercanserteli** [comment]
I confirmed that this happens if you rename the item in an anvil before using it

**Comment by ercanserteli** [comment]
Fixed this in the newest version c133bc54
