### ISSUE TITLE
[Music Maker Mod] Music Box stops working after it is moved with piston (or mods)

### ISSUE THREAD

**Issue by GemHunter1** [ercanserteli/xercamods#34]
Hi, after testing out few things I found out that after you move the Music Box in any way, either using a vanilla piston or any mods (like Create, or Mekanism's Carboard Box). It won't work **until you reinsert the music sheet inside it**. You don't have to replace the instrument, just the music sheet. After that it starts working again, but it is a manual process.

Short video demonstration of bug: [https://streamable.com/1n9nbb](https://streamable.com/1n9nbb)

I am using Valhelsia 3 1.16.5 modpack v3.1.8a

**Comment by ercanserteli** [comment]
Thanks for the pull request. Additionaly, it did not work if it was pushed while powering to the side, that is also fixed now with b90e46e5.
