### ISSUE TITLE
Loot tables overridden, breaking mod compatibility

### ISSUE THREAD

**Issue by gglobensky** [ercanserteli/xercamods#39]
Following a comment dated from April 10th (NotAngel6T4) and an answer dated from April 12th (jack_bagel), there seems to be a problem with the way you create your loot tables for you XercaMusic mod. Loot tables are overridden breaking compatibility with End Remastered amongst other.

ref : https://www.curseforge.com/minecraft/mc-mods/endremastered

Thanks for the unique and amazing mod

**Comment by ercanserteli** [comment]
This issue is now fixed in the latest version 5c3c591f. Thank you.
