### ISSUE TITLE
Crash while picking up Gavel, Prosecutor Badge and Defense Attorney Badge from Creative Inventory

### ISSUE THREAD

**Issue by Catomax262** [ercanserteli/xercamods#42]
Are those unimplemented items?

**Comment by ercanserteli** [comment]
That shouldn't happen, which version are you playing? Also could you post the crash log?

**Comment by Catomax262** [comment]
Wait, let me check real quick

**Comment by Catomax262** [comment]
I think it has something to do with Terra Incognita's "basket drop in" Quark integration

**Comment by ercanserteli** [comment]
Strange, I don't think I can help you with that, I guess you should ask Terra Incognita devs about it.

**Comment by Catomax262** [comment]
Nah, the TI Developer isn't supporting the mod rn. Any attempt is futile.

**Comment by ercanserteli** [comment]
Welp :/
