### ISSUE TITLE
[Question] Exported song format

### ISSUE THREAD

**Issue by MoXAriApph** [ercanserteli/xercamods#46]
Is there any details or any documentation on how the songs are exported? Was looking into a better way to import with the copy / paste function, copying out of minecraft gives what seems to be base64 but filled with weird characters.

**Comment by ercanserteli** [comment]
Sorry, there isn't any documentation on that. When you copy something, the music data as it is represented in the code is converted into characters using base64. The format is also different depending on whether the mod is for before or after the version 1.17. You can copy it out into a text file and copy back to a music sheet in game in a different world, etc. but it is not meant to be interpreted outside the mod. If you want to use or modify it outside the mod in some way, you can look for the code in GuiMusicSheet.java and find out how it works
