### ISSUE TITLE
Cant join server

### ISSUE THREAD

**Issue by Thisguyneedshelp** [ercanserteli/xercamods#63]
Im getting an error thats making it so i cant join server, im pretty certain based on previous peoples' accounts on this error, that its an issue with a recipe, but apparently its notoriously hard to find what mod is causing the issue, i as well dont know which of my 300+ mods it might be, but this was had the last message on the debug before the issue so ill start here, if you could try finding any clue as to which mod it might be if not this one, thatd be very appreciated as i just dont have enough time to sort through them one by one

**Comment by ercanserteli** [comment]
> but this was had the last message on the debug before the issue so ill start here, if you could try finding any clue as to which mod it might be if not this one, thatd be very appreciated as i just dont have enough time to sort through them one by one

Could you share that debug log please?
