### ISSUE TITLE
[MC v 1.19 - with shaders - Joy of painting mod] Any shaders makes the front of the paints transparent 

### ISSUE THREAD

**Issue by Ilianosta** [ercanserteli/xercamods#66]
![2022-11-04_19 26 31](https://user-images.githubusercontent.com/36148265/200083804-2ed79996-2cc8-4379-9345-8f95e2abeb37.png)
The paints are only working when i have no shaders activated, in the moment that i active one of them (anyone of them)

**Comment by ercanserteli** [comment]
While this mod doesn't necessarily support shaders, this issue seems to be fixed thanks to a pull request #65 . Currently the latest forge 1.18.2 and 1.19.2 versions include this fix.
