### ISSUE TITLE
Easel Entity performance impact

### ISSUE THREAD

**Issue by eerussianguy** [ercanserteli/xercamods#68]
https://github.com/ercanserteli/xercamods/blob/5270e5fb86258ec35e442a1c7b825ddbe6056222/XercaPaintMod/src/main/java/xerca/xercapaint/common/entity/EntityEasel.java#L246

![image](https://user-images.githubusercontent.com/59940116/205375336-8f38cfc7-ccaf-4144-a949-c97caba95e60.png)

Obviously spark profiles are to be taken with a grain of salt, but calling move and reapplyPosition every tick causes a lot of collision overhead that's not necessary.

**Comment by ercanserteli** [comment]
That is the simplest gravity implementation I could do. Comparing that to a similar entity like armor stand that calls move() and also a million other things every tick, I think this is fine. If you have a better suggestion, I am happy to change it though. All I want in that part is for the entity to obey gravity in a simple way.

I measured average running times of those two lines, it takes ~15 μs for move and ~1.8 μs for reapplyPosition on my pc. I think it should be fine as is unless you have hundreds of easels in the same region.
