### ISSUE TITLE
Render crash

### ISSUE THREAD

**Issue by JWTHDYTWA** [ercanserteli/xercamods#81]
The client crashes when it's a canvas in the fov.

[Crashlog](https://gist.github.com/JWTHDYTWA/4afc32d6f7610aec4929c65b2e9fc36c), Modpack: TNP6

**Comment by Gbergz** [comment]
It's a Joy of Painting crash.
And to add to this initial report here's version information:

Minecraft: 1.19.2
Forge: 43.2.8
Joy of Painting: 1.0.1

Crash-Report: https://gist.githubusercontent.com/Gbergz/e23983f8db260e46c02cad02f7a90187/raw/547fc46378fd1182cbe27afe12bb199835b90eec/gistfile1.txt

Logs: https://gist.githubusercontent.com/Gbergz/4e69e954227e816b119cfb947af98666/raw/ba585f91e2995c299f13764257b7b73b09f2c2b8/gistfile1.txt

**Comment by Gbergz** [comment]
This is caused by the mod ModernFix and is fixed by updating that mod to version 3.5.2.
