### ISSUE TITLE
Crashes when you click "Singleplayer" (1.19.4)

### ISSUE THREAD

**Issue by Duxtorm** [ercanserteli/xercamods#86]
[crash-2023-06-07_06.34.11-client.txt](https://github.com/ercanserteli/xercamods/files/11668872/crash-2023-06-07_06.34.11-client.txt)
I know this mods is for 1.19.3, and the issue occurred on 1.19.4, but here's the crash log anyway.. iunno, maybe it help T-T

**Comment by ercanserteli** [comment]
I believe this was due to the version discrepancy
