### ISSUE TITLE
Player advancement crash with latest 1.14.4 update

### ISSUE THREAD

**Issue by sixtymillionsqrd** [ercanserteli/xercamods#9]
https://paste.ee/p/BG0QZ

To reproduce create a new world, then close the game and rerun Minecraft. The crash happens when you enter a world for the 2nd time.

Forge 28.2.6

**Comment by sixtymillionsqrd** [comment]
Ok I tested with Forge 28.217 and all the same mods and it works fine. Must be an incompatibility with the latest forge.

**Comment by ercanserteli** [comment]
Ok, I'm closing the issue then. The error in the log doesn't seem specific to xercamod either.

**Comment by sixtymillionsqrd** [comment]
The error only appeared when I updated Xercamod. No other changes to the pack.

**Comment by ercanserteli** [comment]
I see, thanks for the report. Latest forge versions break and fix things all the time, so I only test with the recommended versions.
