### ISSUE TITLE
Joy of Painting: 1.19.4 - 1.20.1 port?

### ISSUE THREAD

**Issue by Cape-City** [ercanserteli/xercamods#90]
How are your plans for bringing it to 1.19.4 or higher?

**Comment by ercanserteli** [comment]
I'll probably do the updates on july

**Comment by Lafolie** [comment]
Hello, would also like to voice my desire for a 1.20.1 mod for Fabric!
Just watched the trailer and it was brilliant. Would love to have this mod on my server :)

**Comment by Lafolie** [comment]
Just saw that 1.20.1 got a Fabric release! Thank you so much <3

**Comment by ercanserteli** [comment]
Thanks, I managed to finish all updates before July ends 😄
