### ISSUE TITLE
Server Crash/No Tick on Startup

### ISSUE THREAD

**Issue by CyanKhaos** [ercanserteli/xercamods#93]
I think we close the server while someone was playing an instrument and the Music Spirit Entity is somehow messing up the start now, i assume it's this mod. Crashlog will be attached here
[crash-2023-07-26_23.42.41-server.txt](https://github.com/ercanserteli/xercamods/files/12177402/crash-2023-07-26_23.42.41-server.txt)
If it is due to this mod a fix would be highly appreciated as we don't want to remove the mod :c

**Comment by ercanserteli** [comment]
Fixed in 0c57c102b730afdb558d03e695db86f16d6ffac7
