### ISSUE TITLE
Xercamusic 1.19.4: not recognized as fabric mod?

### ISSUE THREAD

**Issue by bountifulellie** [ercanserteli/xercamods#97]
I downloaded the 1.19.4 fabric jar.. I'm guessing it was compiled incorrectly because Minecraft apparently isn't recognizing it as a fabric mod

**Comment by ercanserteli** [comment]
Are you sure you downloaded the correct file? I tried with the downloads on both curseforge and modrinth, and it just worked normally on 1.19.4 with fabric.
